# Generated by Django 4.2.7 on 2024-03-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_comment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cmnt',
            new_name='Comment_Box',
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.book'),
        ),
    ]
