# Generated by Django 4.2.7 on 2024-03-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_comment_email_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_Box',
            field=models.TextField(max_length=25),
        ),
    ]
