# Generated by Django 4.2.7 on 2024-03-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_slug'),
        ('book', '0008_alter_comment_comment_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
