# Generated by Django 4.2.7 on 2024-03-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.CharField(blank=True, help_text='In Percentage', max_length=3, null=True),
        ),
    ]
