# Generated by Django 4.2.7 on 2024-03-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
    ]
