# Generated by Django 4.2.7 on 2024-03-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
